<script lang="ts">
	let query = 'terraform security best practices';
</script>

<section class="space-y-8">
	<header class="space-y-3">
		<p class="text-xs font-semibold uppercase tracking-[0.35em] text-slate-500">Knowledge base</p>
		<h2 class="text-3xl font-semibold text-white">Search internal remediation guides</h2>
		<p class="max-w-2xl text-sm text-slate-400">
			The RAG layer will remain in Python. This view will call a new `/knowledge/search` endpoint to retrieve TF-IDF
			results generated by <code class="rounded bg-slate-900/70 px-1 py-0.5 text-xs text-slate-200">backend.rag</code>.
		</p>
	</header>

	<div class="space-y-6 rounded-3xl border border-white/5 bg-slate-950/80 p-6 shadow-xl shadow-slate-950/40">
		<form class="space-y-4">
			<label class="block space-y-2 text-sm font-medium text-slate-200">
				<span>Search term</span>
				<input
					class="w-full rounded-2xl border border-slate-700 bg-slate-900/80 px-4 py-3 text-base text-white shadow-inner shadow-slate-950/60 focus:border-sky-400 focus:outline-none focus:ring-2 focus:ring-sky-400/40"
					type="search"
					placeholder="e.g. AWS S3 encryption, Azure Key Vault purge protection"
					bind:value={query}
				/>
			</label>
			<button class="rounded-2xl bg-sky-500/10 px-4 py-2 text-sm font-semibold text-sky-200 hover:bg-sky-500/20" type="button">
				Search knowledge
			</button>
		</form>

		<section class="space-y-4">
			<h3 class="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500">Preview results</h3>
			<ul class="space-y-4">
				<li class="space-y-2 rounded-2xl border border-white/5 bg-slate-900/70 p-5">
					<p class="text-xs font-semibold uppercase tracking-[0.3em] text-slate-500">knowledge/aws_s3_encryption.md</p>
					<p class="text-sm text-slate-300">
						Terraform S3 buckets should always enable default encryption with KMS-managed keys. Consider using bucket
						policies that refuse unencrypted PUT operations...
					</p>
				</li>
				<li class="space-y-2 rounded-2xl border border-white/5 bg-slate-900/70 p-5">
					<p class="text-xs font-semibold uppercase tracking-[0.3em] text-slate-500">knowledge/azure_key_vault_purge_protection.md</p>
					<p class="text-sm text-slate-300">
						Azure Key Vaults must enable soft delete and purge protection to satisfy CIS benchmarks and ensure no
						administrative user can permanently delete secrets without oversight...
					</p>
				</li>
			</ul>
		</section>
	</div>
</section>
