// Generated by TerraformManager — AWS CloudTrail + Config baseline


provider "aws" {
  region = "us-east-1"
}

locals {
  common_tags = {
    ManagedBy   = "TerraformManager"
    Environment = "prod"
    Owner       = "platform"
    CostCenter  = "ENG"
  }
}

resource "aws_s3_bucket" "org_trail" {
  bucket = "org-trail-logs"
  force_destroy = false
  tags = merge(local.common_tags, { Name = "org_trail-logs" })
}

resource "aws_s3_bucket_public_access_block" "org_trail_pab" {
  bucket                  = aws_s3_bucket.org_trail.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "org_trail_versioning" {
  bucket = aws_s3_bucket.org_trail.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "org_trail_sse" {
  bucket = aws_s3_bucket.org_trail.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_policy" "org_trail_policy" {
  bucket = aws_s3_bucket.org_trail.id
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AWSCloudTrailAclCheck",
      "Effect": "Allow",
      "Principal": { "Service": "cloudtrail.amazonaws.com" },
      "Action": "s3:GetBucketAcl",
      "Resource": "${aws_s3_bucket.org_trail.arn}"
    },
    {
      "Sid": "AWSCloudTrailWrite",
      "Effect": "Allow",
      "Principal": { "Service": "cloudtrail.amazonaws.com" },
      "Action": "s3:PutObject",
      "Resource": "${aws_s3_bucket.org_trail.arn}/AWSLogs/*",
      "Condition": {
        "StringEquals": { "s3:x-amz-acl": "bucket-owner-full-control" }
      }
    }
  ]
}
POLICY
}

resource "aws_cloudwatch_log_group" "org-trail_logs" {
  name              = "/aws/cloudtrail/org-trail"
  retention_in_days = 365
  
  tags              = local.common_tags
}

resource "aws_iam_role" "org-trail_cloudtrail_role" {
  name = "org-trail-cloudtrail"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": { "Service": "cloudtrail.amazonaws.com" },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
  tags = local.common_tags
}

resource "aws_iam_role_policy" "org-trail_cloudtrail_policy" {
  name = "org-trail-cloudtrail-policy"
  role = aws_iam_role.org-trail_cloudtrail_role.id
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "${aws_cloudwatch_log_group.org-trail_logs.arn}:*"
    }
  ]
}
EOF
}

resource "aws_cloudtrail" "org-trail" {
  name                          = "org-trail"
  s3_bucket_name                = aws_s3_bucket.org_trail.id
  cloud_watch_logs_group_arn    = aws_cloudwatch_log_group.org-trail_logs.arn
  cloud_watch_logs_role_arn     = aws_iam_role.org-trail_cloudtrail_role.arn
  is_multi_region_trail         = true
  include_global_service_events = true
  enable_log_file_validation    = true
  
  tags                          = local.common_tags
}

resource "aws_iam_role" "aws-config-role" {
  name = "aws-config-role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": { "Service": "config.amazonaws.com" },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
  tags = local.common_tags
}

resource "aws_iam_role_policy_attachment" "aws-config-role_policy" {
  role       = aws_iam_role.aws-config-role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSConfigRole"
}

resource "aws_config_configuration_recorder" "default" {
  name     = "default"
  role_arn = aws_iam_role.aws-config-role.arn

  recording_group {
    all_supported                 = true
    include_global_resource_types = true
  }
}

resource "aws_config_delivery_channel" "default" {
  name           = "default-channel"
  s3_bucket_name = aws_s3_bucket.org_trail.bucket
  config_snapshot_delivery_properties {
    delivery_frequency = "TwentyFour_Hours"
  }
  depends_on = [aws_config_configuration_recorder.default]
}

resource "aws_config_configuration_recorder_status" "default" {
  name       = aws_config_configuration_recorder.default.name
  is_enabled = true
  depends_on = [aws_config_delivery_channel.default]
}