// Generated by TerraformManager — Azure Key Vault baseline


provider "azurerm" {
  features {}
}

locals {
  tags = {
    ManagedBy   = "TerraformManager"
    Environment = "prod"
    Owner       = "platform"
    CostCenter  = "ENG"
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-kv"
  location = "eastus2"
  tags     = local.tags
}

resource "azurerm_key_vault" "kv" {
  name                        = "kv-secure"
  tenant_id                   = "00000000-0000-0000-0000-000000000000"
  location                    = azurerm_resource_group.rg.location
  resource_group_name         = azurerm_resource_group.rg.name
  sku_name                    = "standard"
  enable_rbac_authorization   = true
  purge_protection_enabled    = true
  soft_delete_enabled         = true
  soft_delete_retention_days  = 90
  public_network_access_enabled = false

  network_acls {
    default_action = "Deny"
    bypass         = ["AzureServices"]
    ip_rules       = ["52.160.0.0/24"]
  }

  tags = local.tags
}

resource "azurerm_private_dns_zone" "kv_dns" {
  name                = "privatelink.vaultcore.azure.net"
  resource_group_name = azurerm_resource_group.rg.name
  tags                = local.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "kv_dns_link" {
  name                  = "kv-secure-dns-link"
  resource_group_name   = azurerm_resource_group.rg.name
  private_dns_zone_name = azurerm_private_dns_zone.kv_dns.name
  virtual_network_id    = "/subscriptions/.../virtualNetworks/vnet-secure"
  tags                  = local.tags
}

resource "azurerm_private_endpoint" "kv_pe" {
  name                = "kv-secure-pe"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  subnet_id           = "/subscriptions/.../subnets/kv-endpoint"
  tags                = local.tags

  private_service_connection {
    name                           = "kv-secure-psc"
    private_connection_resource_id = azurerm_key_vault.kv.id
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "kv-secure-dns-group"
    private_dns_zone_ids = [azurerm_private_dns_zone.kv_dns.id]
  }
}
