// Generated by TerraformManager


provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-app"
  location = "eastus"
  tags = {
    ManagedBy   = "TerraformManager"
    Environment = "prod"
    Owner       = "platform"
    CostCenter  = "ENG"
  }
}

resource "azurerm_storage_account" "sa" {
  name                     = "stapp1234567890"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  allow_blob_public_access  = false
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"
  blob_properties {
    versioning_enabled = true
  }
  
  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices"]
    ip_rules                   = ["10.0.0.0/24","10.0.1.0/24"]
  }
  
  tags = {
    ManagedBy   = "TerraformManager"
    Environment = "prod"
    Owner       = "platform"
    CostCenter  = "ENG"
  }
}


resource "azurerm_private_endpoint" "stapp1234567890_pe" {
  name                = "stapp1234567890-pe"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  subnet_id           = "/subscriptions/.../subnets/storage-private-endpoint"

  private_service_connection {
    name                           = "stapp1234567890-blob"
    private_connection_resource_id = azurerm_storage_account.sa.id
    subresource_names              = ["blob"]
    is_manual_connection           = false
  }

  
  private_dns_zone_group {
    name                 = "stapp1234567890_blob_zone"
    private_dns_zone_ids = ["/subscriptions/.../privateDnsZones/privatelink.blob.core.windows.net"]
  }
  

  tags = {
    ManagedBy   = "TerraformManager"
    Environment = "prod"
    Owner       = "platform"
    CostCenter  = "ENG"
  }
}

output "storage_private_endpoint_id" {
  value       = azurerm_private_endpoint.stapp1234567890_pe.id
  description = "Resource ID for the storage account private endpoint."
}
