// Generated by TerraformManager — Azure AKS baseline


provider "azurerm" {
  features {}
}

locals {
  tags = {
    ManagedBy   = "TerraformManager"
    Environment = "prod"
    Owner       = "platform"
    CostCenter  = "ENG"
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-aks"
  location = "eastus2"
  tags     = local.tags
}

resource "azurerm_log_analytics_workspace" "aks-secure_law" {
  name                = "aks-secure-law"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.tags
}

resource "azurerm_kubernetes_cluster" "aks-secure" {
  name                = "aks-secure"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  dns_prefix          = "akssecure"
  kubernetes_version  = "1.29.2"
  sku_tier            = "Standard"
  role_based_access_control_enabled = true
  azure_active_directory_role_based_access_control {
    managed = true
  }
  identity {
    type = "SystemAssigned"
  }
  private_cluster_enabled        = true
  public_network_access_enabled  = false
  api_server_authorized_ip_ranges = []

  default_node_pool {
    name                = "nodepool1"
    node_count          = 3
    vm_size             = "Standard_D4s_v5"
    vnet_subnet_id      = "/subscriptions/.../resourceGroups/rg-aks/providers/Microsoft.Network/virtualNetworks/vnet/subnets/aks"
    enable_auto_scaling = true
    min_count           = 3
    max_count           = 6
    tags                = local.tags
    orchestrator_version = "1.29.2"
    max_pods            = 110
  }

  network_profile {
    network_plugin      = "azure"
    network_policy      = "azure"
    load_balancer_sku   = "standard"
    outbound_type       = "loadBalancer"
    service_cidr        = "10.2.0.0/16"
    dns_service_ip      = "10.2.0.10"
    docker_bridge_cidr  = "172.17.0.1/16"
  }

  addon_profile {
    oms_agent {
      enabled                   = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.aks-secure_law.id
    }
    azure_policy {
      enabled = true
    }
  }

  api_server_access_profile {
    authorized_ip_ranges = []
  }

  tags = local.tags
}

resource "azurerm_monitor_diagnostic_setting" "aks-secure_diag" {
  name                       = "aks-secure-diag"
  target_resource_id         = azurerm_kubernetes_cluster.aks-secure.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.aks-secure_law.id

  log {
    category = "kube-apiserver"
    enabled  = true
  }
  log {
    category = "kube-audit"
    enabled  = true
  }
  log {
    category = "kube-audit-admin"
    enabled  = true
  }
  log {
    category = "kube-controller-manager"
    enabled  = true
  }
  log {
    category = "kube-scheduler"
    enabled  = true
  }
  log {
    category = "cluster-autoscaler"
    enabled  = true
  }
  log {
    category = "guard"
    enabled  = true
  }
  metric {
    category = "AllMetrics"
    enabled  = true
  }
}
