// Generated by TerraformManager — Azure diagnostics baseline


provider "azurerm" {
  features {}
}

locals {
  tags = {
    ManagedBy   = "TerraformManager"
    Environment = "prod"
    Owner       = "platform"
    CostCenter  = "ENG"
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-diag"
  location = "eastus"
  tags     = local.tags
}

resource "azurerm_log_analytics_workspace" "law" {
  name                = "law-diag"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.tags
}


resource "azurerm_storage_account" "logstorage" {
  name                     = "logstorageacct"
  location                 = azurerm_resource_group.rg.location
  resource_group_name      = azurerm_resource_group.rg.name
  account_tier             = "Standard"
  account_replication_type = "LRS"
  allow_blob_public_access  = false
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"
  tags = local.tags
}



resource "azurerm_monitor_diagnostic_setting" "diag_storage" {
  name                       = "diag-1"
  target_resource_id         = azurerm_storage_account.logstorage.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  
  storage_account_id         = azurerm_storage_account.logstorage.id
  

  
  enabled_log {
    category = "StorageRead"
  }
  
  enabled_log {
    category = "StorageWrite"
  }
  
  enabled_log {
    category = "StorageDelete"
  }
  

  
  enabled_metric {
    category = "AllMetrics"
  }
  
}



resource "azurerm_monitor_metric_alert" "law_health" {
  name                = "law-ingestion-alert"
  resource_group_name = azurerm_resource_group.rg.name
  scopes              = [azurerm_log_analytics_workspace.law.id]
  description         = "Alert when ingestion availability drops below 99%"
  severity            = 2
  frequency           = "PT5M"
  window_size         = "PT5M"
  enabled             = true

  criteria {
    metric_namespace = "microsoft.operationalinsights/workspaces"
    metric_name      = "SearchServiceAvailability"
    aggregation      = "Average"
    operator         = "LessThan"
    threshold        = 99
  }

  
  action {
    action_group_id = "/subscriptions/.../actionGroups/notify"
  }
  

  tags = local.tags
}


output "log_analytics_workspace_id" {
  value = azurerm_log_analytics_workspace.law.id
}

output "log_analytics_workspace_workspace_id" {
  value = azurerm_log_analytics_workspace.law.workspace_id
}


output "diagnostics_storage_account_id" {
  value = azurerm_storage_account.logstorage.id
}

output "diagnostics_storage_account_primary_blob_endpoint" {
  value = azurerm_storage_account.logstorage.primary_blob_endpoint
}


output "diagnostic_setting_ids" {
  value = {
  
    "diag_storage" = azurerm_monitor_diagnostic_setting.diag_storage.id
  
  }
}

output "diagnostic_target_resource_ids" {
  value = {
  
    "diag_storage" = azurerm_monitor_diagnostic_setting.diag_storage.target_resource_id
  
  }
}


output "diagnostics_health_alert_id" {
  value       = azurerm_monitor_metric_alert.law_health.id
  description = "Metric alert monitoring Log Analytics ingestion health."
}
