// Generated by TerraformManager — Kubernetes HPA + PDB baseline


provider "kubernetes" {
  host                   = var.kube_host
  token                  = var.kube_token
  cluster_ca_certificate = base64decode(var.kube_ca)
}

variable "kube_host" { description = "https://your-api-server:6443" }
variable "kube_token" { description = "Service account token" }
variable "kube_ca"    { description = "Base64-encoded cluster CA" }

locals {
  labels = {
    app         = "my-app"
    environment = "prod"
    managed_by  = "TerraformManager"
  }
}

resource "kubernetes_horizontal_pod_autoscaler_v2" "my_app_hpa" {
  metadata {
    name      = "my-app-hpa"
    namespace = "apps"
    labels    = local.labels
  }

  spec {
    min_replicas = 2
    max_replicas = 6
    scale_target_ref {
      api_version = "apps/v1"
      kind        = "Deployment"
      name        = "my-app"
    }

    metric {
      type = "Resource"
      resource {
        name = "cpu"
        target {
          type                = "Utilization"
          average_utilization = 60
        }
      }
    }

    
  }
}

resource "kubernetes_pod_disruption_budget" "my_app_pdb" {
  metadata {
    name      = "my-app-pdb"
    namespace = "apps"
    labels    = local.labels
  }

  spec {
    
    min_available = "1"
    
    selector {
      match_labels = {
        app = "my-app"
      }
    }
  }
}